apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"einvoice-application-cluster1"},"name":"application","namespace":"einvoice-cluster1"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"einvoice-application-cluster1"}},"template":{"metadata":{"labels":{"app":"einvoice-application-cluster1"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"node.role","operator":"In","values":["einvoice-cluster1"]}]}]}},"podAntiAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"podAffinityTerm":{"labelSelector":{"matchExpressions":[{"key":"app","operator":"In","values":["einvoice-application-cluster1"]}]},"topologyKey":"kubernetes.io/hostname"},"weight":1}]}},"containers":[{"envFrom":[{"configMapRef":{"name":"application-config"}}],"image":"registry.kcntt.net/hddt/einvoice-application-vtt","name":"einvoice-application-cluster1","ports":[{"containerPort":8041,"name":"http"}],"resources":{}}]}}}}
  creationTimestamp: "2023-05-26T15:50:32Z"
  generation: 15
  labels:
    app: einvoice-application-cluster1
  name: application
  namespace: einvoice-cluster1
  resourceVersion: "35472996"
  uid: 99b86c1c-37c7-4f41-ba9f-49c921396f34
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: einvoice-application-cluster1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-06-16T04:19:17Z"
      creationTimestamp: null
      labels:
        app: einvoice-application-cluster1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.role
                operator: In
                values:
                - einvoice-cluster1
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - einvoice-application-cluster1
              topologyKey: kubernetes.io/hostname
            weight: 1
      containers:
      - envFrom:
        - configMapRef:
            name: application-config
        image: registry.kcntt.net/hddt/einvoice-application-vtt
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /k8s/health/liveness
            port: http
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 15
        name: einvoice-application-cluster1
        ports:
        - containerPort: 8041
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /k8s/health/readiness
            port: http
            scheme: HTTP
          initialDelaySeconds: 90
          periodSeconds: 12
          successThreshold: 1
          timeoutSeconds: 15
        resources:
          limits:
            cpu: 2700m
            memory: 22Gi
          requests:
            cpu: 1350m
            memory: 11Gi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /tmp
          name: tmp
        - mountPath: /app/logs
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: tmp
      - hostPath:
          path: /u01/einvoice/logs
          type: Directory
        name: logs
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2023-06-14T16:57:45Z"
    lastUpdateTime: "2023-06-14T16:57:45Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-05-26T15:50:32Z"
    lastUpdateTime: "2023-06-21T15:41:19Z"
    message: ReplicaSet "application-57b4bb547f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
