---
# Source: einvoice-application/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: einvoice-application-cluster1
  name: application
  namespace: einvoice-cluster1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: einvoice-application-cluster1
  template:
    metadata:
      labels:
        app: einvoice-application-cluster1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node.role
                    operator: In
                    values: [einvoice-cluster1]
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - einvoice-application-cluster1
                topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: tmp
          emptyDir: {}
        - name: logs
          hostPath:
            path: /u01/einvoice/logs
            type: Directory
      containers:
        - envFrom:
            - configMapRef:
                name: application-config
          image: registry.kcntt.net/hddt/einvoice-application-vtt
          name: einvoice-application-cluster1
          ports:
            - name: http
              containerPort: 8041
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: logs
              mountPath: /app/logs
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /k8s/health/liveness
              port: http
            initialDelaySeconds: 90
            timeoutSeconds: 15
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /k8s/health/readiness
              port: http
            initialDelaySeconds: 90
            timeoutSeconds: 15
            periodSeconds: 12
            successThreshold: 1
            failureThreshold: 3
