version: '2.2'
services:
  tctn_application_ins:
    network_mode: host
    image: 10.60.156.72/hddt/tctn-application-master
    scale : 1
    volumes:
      - ./logs:/logs
    ports:
      - '8040:8040'
    environment:
      - SERVER_PORT=8050
      - _JAVA_OPTIONS=-Xmx4096m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,prod-mini,no-liquibase
  tctn_application_ins_2:
    network_mode: host
    image: 10.60.156.72/hddt/tctn-application-master
    scale : 2
    volumes:
      - ./logs:/logs
    ports:
      - '8040:8040'
    environment:
      - SERVER_PORT=8052
      - _JAVA_OPTIONS=-Xmx4096m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,prod-mini,no-liquibase
  tctn_application_ins_3:
    network_mode: host
    image: 10.60.156.72/hddt/tctn-application-master
    scale : 1
    volumes:
      - ./logs:/logs
    ports:
      - '8040:8040'
    environment:
      - SERVER_PORT=8054
      - _JAVA_OPTIONS=-Xmx4096m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,prod-mini,no-liquibase